"""Shared primitives for the proposed contract: IDs, time, provenance, errors, pagination."""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from ..api.schemas import ID_PATTERN

StableId = Annotated[str, Field(pattern=ID_PATTERN, max_length=128)]
UtcTime = Annotated[AwareDatetime, Field(description="ISO-8601 UTC timestamp ending in Z; naive input is rejected.")]
ShortText = Annotated[str, Field(min_length=1, max_length=500)]

MachineId = Annotated[str, Field(
    pattern=ID_PATTERN, max_length=128,
    description="Exact catalog asset ID. Checked against the verified catalog when a session is created (since "
                "I02a); "
                "an unknown ID is rejected with 422 unknown_machine.",
    examples=["EXC_DEMO_001", "DOZ_DEMO_001", "LDR_DEMO_001", "TRK_DEMO_001", "BHL_DEMO_001"],
)]
OperatorId = Annotated[str, Field(pattern=ID_PATTERN, max_length=128, examples=["OP_DEMO_1_1"])]
SiteId = Annotated[str, Field(pattern=ID_PATTERN, max_length=128, examples=["SITE_FIXTURE_A"])]
ZoneId = Annotated[str, Field(pattern=ID_PATTERN, max_length=128, examples=["ZONE_FIXTURE_A_PIT"])]
ShiftId = Annotated[str, Field(pattern=ID_PATTERN, max_length=128, examples=["EXC_DEMO_001_2026-08-25"])]
Sha256 = Annotated[str, Field(pattern=r"^[0-9a-f]{64}$")]


class Strict(BaseModel):
    """Every proposed model rejects unknown fields, so private data cannot ride along in a public projection."""

    model_config = ConfigDict(extra="forbid")


Origin = Literal[
    "synthetic",               # generated by the versioned dataset generator
    "synthetic_contract_fixture",  # invented for a contract example only; never a dataset field or measurement
    "simulator",               # emitted by the backend simulator / dataset replay
    "provided_unverified",     # supplied source rows with unverified provenance
    "device",                  # a real device or detector (future adapters)
    "provider",                # an external provider such as Open-Meteo
    "runtime",                 # created by an actual backend workflow
    "assumption_based",        # labelled engineering assumption (e.g. vitals before WESAD processing)
]


class Provenance(Strict):
    origin: Origin
    is_simulated: bool = Field(description="True for anything that is not a real-world measurement.")
    source_id: StableId | None = Field(default=None, description="Dataset record, device, detector or provider ID.")
    source_version: str | None = Field(default=None, max_length=64)
    dataset_manifest_sha256: Sha256 | None = Field(
        default=None, description="Manifest hash of the dataset snapshot a replayed value came from.")


Quality = Literal["good", "degraded", "stale", "unknown"]


ProposedErrorCode = Literal[
    # existing v1 codes (unchanged meaning)
    "unauthorized", "not_found", "validation_error", "idempotency_conflict", "session_conflict",
    "llm_unavailable", "turn_failed", "internal_error",
    # implemented in I02a (runtime): new-session catalog admission
    "unknown_machine", "unknown_operator", "catalog_unavailable",
    # implemented in I02b (runtime): actor authentication
    "forbidden",               # 403: authenticated principal lacks scope for this resource
    "auth_unavailable",        # 503: token store unreadable; never treated as success
    # proposed additions (additive per API_CONTRACT.md)
    "invalid_cursor",          # 422: negative, future, foreign or inconsistent after/Last-Event-ID
    "replay_expired",          # 410: required stream history is past retention; use recovery.status_url
    "version_conflict",        # 409: expected_version is stale
    "decision_conflict",       # 409: contradictory decision for the same approval
    "approval_expired",        # 409: proposal expired before the decision
    "consent_required",        # 403: purpose-specific consent is missing or revoked
    "rate_limited",            # 429: admission limit reached; Retry-After set
    "payload_too_large",       # 413
    "capability_unavailable",  # 503: the route's target stage is not implemented yet in this deployment
]


class RecoveryInfo(Strict):
    status_url: str | None = Field(default=None, max_length=512,
                                   description="Authoritative status to read instead of retrying blindly.")
    resume_after: int | None = Field(default=None, ge=0, description="Cursor to resume from when replay is possible.")
    retry_after_ms: int | None = Field(default=None, ge=0)


class ProposedErrorDetail(Strict):
    field: str = Field(max_length=256)
    issue: str = Field(max_length=500)


class ProposedErrorBody(Strict):
    code: ProposedErrorCode
    message: str = Field(max_length=500, description="Sanitized. Never a stack trace or raw provider payload.")
    retryable: bool
    request_id: str = Field(max_length=128)
    details: list[ProposedErrorDetail] | None = None
    recovery: RecoveryInfo | None = None


class ProposedErrorResponse(Strict):
    error: ProposedErrorBody


class PageInfo(Strict):
    next_cursor: str | None = Field(default=None, max_length=256,
                                    description="Opaque; absent when there are no more items.")
    has_more: bool
