"""Silero VAD (worker settings) on SYNTHETIC cab-noise fixtures, offline.

Noise-only fixtures must not look like speech (they would cause false barge-in). The speech
positive control uses local Windows SAPI speech generated by scripts/make_speech_fixtures.ps1
(git-ignored); those tests skip when the fixture is absent. Krisp is not in this path: it needs a
LiveKit Cloud session. None of this replaces a real microphone/speakerphone test.
"""

from __future__ import annotations

import asyncio
import wave
from pathlib import Path

import pytest
from livekit import rtc
from livekit.agents import vad as vadmod

from cocoon_voice.live_checks import mix
from cocoon_voice.noise_fixtures import KINDS, generate, scale_to_snr
from cocoon_voice.providers import load_vad

FIXTURES = Path(__file__).parent / "fixtures" / "audio"


@pytest.fixture(scope="module")
def vad():
    return load_vad()


async def vad_segments(vad, pcm: bytes, rate: int = 16000) -> tuple[int, float]:
    stream = vad.stream()
    starts, speech_s = 0, 0.0

    async def feed():
        step = rate // 50 * 2
        for i in range(0, len(pcm), step):
            chunk = pcm[i:i + step]
            stream.push_frame(rtc.AudioFrame(chunk, rate, 1, len(chunk) // 2))
        stream.end_input()

    feeder = asyncio.create_task(feed())
    async for ev in stream:
        if ev.type == vadmod.VADEventType.START_OF_SPEECH:
            starts += 1
        elif ev.type == vadmod.VADEventType.END_OF_SPEECH:
            speech_s += ev.speech_duration
    await feeder
    return starts, speech_s


@pytest.mark.parametrize("kind", KINDS)
@pytest.mark.parametrize("level", [-24.0, -12.0])
async def test_noise_alone_is_not_speech(vad, kind, level):
    starts, _ = await vad_segments(vad, generate(kind, seconds=8, level_dbfs=level))
    assert starts == 0, f"{kind} at {level} dBFS would trigger a false barge-in"


def _speech() -> tuple[bytes, int]:
    path = FIXTURES / "sapi_hey_cat_question.wav"
    if not path.exists():
        pytest.skip("speech fixture missing: run scripts/make_speech_fixtures.ps1 (Windows)")
    with wave.open(str(path)) as w:
        return w.readframes(w.getnframes()), w.getframerate()


@pytest.mark.parametrize("kind", KINDS)
@pytest.mark.parametrize("snr_db", [10, 0])
async def test_speech_under_noise_is_one_unbroken_segment(vad, kind, snr_db):
    speech, rate = _speech()
    pad = b"\x00\x00" * rate
    clip = pad + speech + pad
    noise = scale_to_snr(speech, generate(kind, seconds=len(clip) / 2 / rate + 1, sample_rate=rate), snr_db)
    starts, speech_s = await vad_segments(vad, mix(clip, noise), rate)
    utterance_s = len(speech) / 2 / rate
    assert starts == 1, "a mid-sentence split would end the user's turn early"
    assert 0.7 * utterance_s <= speech_s <= utterance_s + 0.6
